=== repo22024/XML-DTD/Arman/empresa.dtd
<!ELEMENT Empresa (Empleados, Proyectos)>

<!ELEMENT Empleados (Empleado+)>
<!ELEMENT Empleado (NombreEmpleado, Departamento, ProyectoAsignado*)>
<!ATTLIST Empleado IdEmpleado ID #REQUIRED>
<!ATTLIST Empleado FechaContrato CDATA #REQUIRED>

<!ELEMENT IdEmpleado (#PCDATA)>
<!ELEMENT FechaContrato (#PCDATA)>
<!ELEMENT NombreEmpleado (#PCDATA)>
<!ELEMENT Departamento (#PCDATA)>
<!ELEMENT ProyectoAsignado (#PCDATA)>



<!ELEMENT Proyectos (Proyecto+)>
<!ELEMENT Proyecto (NombreProyecto)>
<!ATTLIST Proyecto IdProyecto ID #REQUIRED>
<!ATTLIST Proyecto Estado (Activo|Completado|Pausado) #REQUIRED>

<!ELEMENT NombreProyecto (#PCDATA)>

=== repo22024/XML-DTD/Arman/empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Empresa PUBLIC "public-id" "empresa.dtd">

<Empresa>
    <Empleados>
        <Empleado IdEmpleado="E001" FechaContrato="2024-01-01">
            <NombreEmpleado>Jose Perez</NombreEmpleado>
            <Departamento>Administracion</Departamento>
            <ProyectoAsignado>P001</ProyectoAsignado>
        </Empleado>

        <Empleado IdEmpleado="E002" FechaContrato="2022-02-01">
            <NombreEmpleado>Marcos Parra</NombreEmpleado>
            <Departamento>Ingenieria</Departamento>
            <ProyectoAsignado>P002, P003</ProyectoAsignado>
        </Empleado>

        <Empleado IdEmpleado="E003" FechaContrato="2023-03-01">
            <NombreEmpleado>Jonathan Malave</NombreEmpleado>
            <Departamento>Ingenieria</Departamento>
            <ProyectoAsignado>P003</ProyectoAsignado>
        </Empleado>
    </Empleados>
       
    <Proyectos>
        <Proyecto IdProyecto="P001" Estado="Activo">
            <NombreProyecto>Alfa</NombreProyecto>
        </Proyecto>

        <Proyecto IdProyecto="P002" Estado="Activo">
            <NombreProyecto>Beta</NombreProyecto>
        </Proyecto>

        <Proyecto IdProyecto="P003" Estado="Activo">
            <NombreProyecto>Gamma</NombreProyecto>
        </Proyecto>
    </Proyectos>
</Empresa>
