=== repo22024/XML-DTD/Dani/videogames/videogames.dtd
<!ELEMENT biblioteca (videojuego+)>
<!ELEMENT videojuego (titulo, precio, stock)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT stock (#PCDATA)>

<!-- Restricciones de valores aceptados para plataforma -->
<!ATTLIST videojuego plataforma (PC|PS5|Xbox) #REQUIRED>
<!ATTLIST videojuego idvideojuego ID #REQUIRED>

=== repo22024/XML-DTD/Dani/videogames/videogames.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca PUBLIC "public-id" "videogames.dtd">
<!-- <?xml-model href="videogamesVal.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?> -->
<biblioteca>
    <!-- El [precio] y [stock] debe ser entero no negativo -->
    <videojuego idvideojuego="V001" plataforma="PS5">
        <titulo>Grand Theif Auto San Andreas</titulo>
        <precio>59.99</precio>
        <stock>20</stock>
    </videojuego>
    
    <videojuego idvideojuego="V002" plataforma="Xbox">
        <titulo>Halo Infinite</titulo>
        <precio>49.99</precio>
        <stock>15</stock>
    </videojuego>
    
    <videojuego idvideojuego="V003" plataforma="PC">
        <titulo>Cyberpunk 2077</titulo>
        <precio>39.99</precio>
        <stock>25</stock>
    </videojuego>
</biblioteca>
