=== repo22024/XML-DTD/Rafa/tienda.dtd
<!ELEMENT tienda (comidas,clientes)>
<!ELEMENT comidas (comida+)>
<!ELEMENT comida (nombrecomida,precio,peso)>
<!ATTLIST comida idcomida ID #REQUIRED>
<!ATTLIST comida especie  (perro | gato | conejo | indefinido) #REQUIRED>
<!ELEMENT nombrecomida (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT unidad (#PCDATA)>
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (nombrecliente,telefono)>
<!ATTLIST cliente idcliente ID #REQUIRED>
<!ELEMENT nombrecliente (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

=== repo22024/XML-DTD/Rafa/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Inicio para asociar el XML a un archivo validador (DTD o XSD) a conveniencia, si se usa uno, desactivar el otro poniéndolo como comentario-->
<!--<!DOCTYPE tienda PUBLIC "public-id" "tienda.dtd">--><!--Esta linea sirve para validar el documento XML mediante un documento DTD-->
<?xml-model href="tienda.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?><!--Esta linea sirve para validar el documento XML mediante un documento XSD-->
<!--Fin de las sentencias para validar el documento-->
<tienda>
<comidas>
    <comida idcomida="CA001" especie="Gato">
        <nombrecomida>Delicias Gatunas</nombrecomida>
        <precio>45.25</precio> 
        <peso>2.5</peso>
        <unidad>Kg</unidad>
    </comida>
    <comida idcomida="CA002" especie="Perro">
        <nombrecomida>Galletas Guau</nombrecomida>
        <precio>7.25</precio> 
        <peso>0.750</peso>
        <unidad>Gr</unidad>
    </comida>
    <comida idcomida="CA003" especie="Conejo">
        <nombrecomida>Hinojo Fresco</nombrecomida>
        <precio>2.5</precio> 
        <peso>0.250</peso>
        <unidad>Kg</unidad>
    </comida>
    <comida idcomida="CA004" especie="Gato">
        <nombrecomida>Wiskas seca</nombrecomida>
        <precio>12.50</precio> 
        <peso>4.00</peso>
        <unidad>Kg</unidad>
    </comida>
    <comida idcomida="CA005" especie="Perro">
        <nombrecomida>Friskis</nombrecomida>
        <precio>3.50</precio> 
        <peso>0.50</peso>
        <unidad>Kg</unidad>
    </comida>
</comidas>

<clientes>
<cliente idcliente="C001">
    <nombrecliente>Carlos Santana</nombrecliente>
    <telefono>922505475</telefono>
</cliente>
<cliente idcliente="C002">
    <nombrecliente>Pedro Guerra</nombrecliente>
    <telefono>922547215</telefono>
</cliente>
<cliente idcliente="C003">
    <nombrecliente>Rubinos Pérez</nombrecliente>
    <telefono>620457896</telefono>
</cliente>
</clientes>
</tienda>
